uploads = []
outputs = []

[[generated]]
id = "F1_i4hZ1AmQ3ZoJZ1-Yug"
uri = "file://artifacts/marketing/public/images/hero-data.png"
type = "image"
title = "generated_image"

[[generated]]
id = "T9ea_mIXccibNumtNtez6"
uri = "file://artifacts/marketing/public/images/dashboard-mockup.png"
type = "image"
title = "generated_image"
